version: "3"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    restart: always
    ports: 
      - 9200:9200
      - 9300:9300
    environment: 
      discovery.type: single-node
    networks:
      - elastic
  
  kibana01:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana01
    restart: always
    ports: 
      - 5601:5601
    environment: 
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge